// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0EfjB9QFaTGAgtJdjEx9Wj8UKWZevU7s',
    appId: '1:349828504920:web:30aa24e6f27cbd680e992d',
    messagingSenderId: '349828504920',
    projectId: 'ground-admin-22692',
    authDomain: 'ground-admin-22692.firebaseapp.com',
    storageBucket: 'ground-admin-22692.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPpNbO5NtlNer8don2owixbrYHhNWd78',
    appId: '1:349828504920:android:135cad359a0425650e992d',
    messagingSenderId: '349828504920',
    projectId: 'ground-admin-22692',
    storageBucket: 'ground-admin-22692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmA0Pba3jJPBg8izyWEbg3SAiwNBk8TY',
    appId: '1:349828504920:ios:b1bbbb047214d51b0e992d',
    messagingSenderId: '349828504920',
    projectId: 'ground-admin-22692',
    storageBucket: 'ground-admin-22692.appspot.com',
    iosClientId: '349828504920-dvi83ug13natk6pr8fubpikipvi672uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendGrounda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmA0Pba3jJPBg8izyWEbg3SAiwNBk8TY',
    appId: '1:349828504920:ios:b1bbbb047214d51b0e992d',
    messagingSenderId: '349828504920',
    projectId: 'ground-admin-22692',
    storageBucket: 'ground-admin-22692.appspot.com',
    iosClientId: '349828504920-dvi83ug13natk6pr8fubpikipvi672uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendGrounda',
  );
}
